# Conda Environment Setup Instructions
#
#    conda env create -f environment.yml
#    conda env update --file environment.yml --prune
#    conda env export --name superwised-machine-learning-exercises > environment.yml
#    conda env remove --name superwised-machine-learning-exercises
#    conda env list

name: superwised-machine-learning-exercises
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.15
  - pip
  - bottleneck
  - pip:
      - numpy==1.23.5
      - pandas==1.5.2
      - ipykernel==6.17.1
      - ipython==8.7.0
      - jupyter-client==7.4.7
      - jupyter-core==5.1.0
      - matplotlib==3.6.2
      - scipy==1.9.3
      - scikit-learn==1.2.0
      - seaborn==0.12.1